### PR TITLE
Fix AlphaChange being incorrectly calculated after a color change

### LINKED ISSUE #88: Changing alpha and colour at the same time does not change the colour
Currently `glyph_brush` does not allow changing the alpha and the colour of text at the same time, if the text itself does not change.

[Here's a gist](https://gist.github.com/Ryan1729/4cc66eb26f28e81d52cc3ac8d71cf8a5) containing a small change to the example that demonstrates this.

In that version, the alpha changes continuously, and typing anything should toggle the text to be either colourful or grayscale. But the colours remain unchanged. If you comment out line 231 where the `alpha` variable is incremented, then the colour toggling works as expected.

After doing a bit of digging, I found that changing the colour and the alpha at the same time results in the `SectionHashDetail`s that get passed to the `diff` method having identical `geometry` and `text_no_color_alpha` field values, but different values in all the other fields. In the [current implementation of the `diff` method](https://github.com/alexheretic/glyph-brush/blob/fc1a24dc4bd222f65dba44392e8d852e71642433/glyph-brush/src/glyph_brush.rs#L625-L636) this results in `SectionHashDiff::AlphaChange` being returned, which, of course, results in only the alpha changing.

If I change the `diff` method to return `SectionHashDiff::ColorChange` where it previously returned `SectionHashDiff::AlphaChange` then everything seems to work, since the colour includes the alpha value. But, I'm not sure whether there would be other effects elsewhere, or if that would adversely affect performance in important cases.

### PR DESCRIPTION
**Pull request by alexheretic**
Fix dodgy logic that can consider a change to both color & alpha as an alpha only change. I've reworked the code to be easier to read & added `hash_diff_test` tests for this area of logic.

Fixes #88

### CODE REVIEW

File: glyph-brush/src/glyph_brush.rs [hunk 1]
```diff
@@ -599,40 +597,40 @@ impl SectionHashDetail {
...
-        if self.text == other.text {
-            return SectionHashDiff::GeometryChange;
+    fn diff(self, other: SectionHashDetail) -> GlyphChange {
+        if self.test_alpha_color == other.test_alpha_color {
+            return GlyphChange::Geometry(self.geometry);
         } else if self.geometry == other.geometry {
-            if self.text_no_color == other.text_no_color {
-                return SectionHashDiff::ColorChange;
-            } else if self.text_no_color_alpha == other.text_no_color_alpha {
-                return SectionHashDiff::AlphaChange;
```
Comment (alexheretic) [inline glyph-brush/src/glyph_brush.rs]: The issue was here, and with my dodgy naming making it hard (for me) to think about this.

Here it says `text+alpha is different && text is same ==> only alpha has changed` which is wrong as the color **and** alpha may have changed.
