### PR TITLE
Fix pixel bound usage in word layout

### LINKED ISSUE #87: `glyph_bounds` returning incorrect values with Arial font
Hey, I have been using `GlyphBrush::glyph_bounds` nicely for a while (see #68). However, a user of `iced` just reported a weird case.

If I am not mistaken, this snippet should display the text in a single line:

```rust
let section = Section {
    text: "Eins Zwei Drei Vier Funf",
    scale: Scale::uniform(20.0),
    ..Section::default()
};

let bounds = glyph_brush.glyph_bounds(&section).unwrap();

glyph_brush.queue(Section {
    bounds: (bounds.width(), bounds.height()),
    ..section
});
```

However, when using the Arial font, the last word of the text is cut off:

image

The reported bounds are:

```
&bounds = Rect {
    min: Point {
        x: 0.0,
        y: 0.0,
    },
    max: Point {
        x: 192.67482,
        y: 20.0,
    },
}
```

At first, I thought it could be a precision issue, but even if I `ceil` the width to `193.0`, the issue still occurs. Any ideas what may be going on? I have only been able to reproduce the issue with the Arial font so far (__update:__ it seems to also happen with the OpenSans Light font). [Here is the full SSCCE](https://gist.github.com/hecrj/3f6c2aed1055ccd2ee634af372ed1e48).

### PR DESCRIPTION
**Pull request by alexheretic**
Fixes #87 by tracking word layout width with & without trailing space but without using any glyph pixel bounds.

Avoiding using the glyph pixel bounds to measure word width actually simplifies the code a little, the new code has clearer intent too I think.

Reproduce #87 with tests:
* glyph_bound_section_bound_consistency
* glyph_bound_section_bound_consistency_trailing_space

@hecrj Does this fix the issue for you?

### CODE REVIEW

File: glyph-brush-layout/src/lines.rs [hunk 1]
```diff
@@ -102,9 +102,8 @@ impl<'font, L: LineBreaker, F: FontMap<'font>> Iterator for Lines<'_, '_, 'font,
         let mut progressed = false;
 
         while let Some(word) = self.words.peek() {
-            let word_max_x = word.bounds.map(|b| b.max.x).unwrap_or(word.layout_width);
             // only if `progressed` means the first word is allowed to overlap the bounds
-            if progressed && (caret.x + word_max_x).ceil() > self.width_bound {
+            if progressed && caret.x + word.layout_width_no_trail > self.width_bound {
```
Comment (alexheretic) [inline glyph-brush-layout/src/lines.rs]: This has clearer intent now too. I'm not sure what my idea was with the `ceil` before.

It's worth noting that using glyph_bounds as bounds can still fail due to floating point accuracy loss. I'm not sure if it's worth trying to deal with that here, ie allow relative equality.

Comment (alexheretic) [reply glyph-brush-layout/src/lines.rs]: I've reproduced and fixed the fp error case in #91

**Comment by hecrj** [comment]
Yes! This does indeed fix the issue for me.

Thank you again for the fast response and quick support!

File: glyph-brush-layout/src/words.rs [hunk 2]
```diff
@@ -117,25 +118,18 @@ where
...
+                caret += advance_width;
 
+                if positioned.bounds().is_some() {
                     glyphs.push((positioned, color, font_id));
-                }
 
-                caret.x += advance_width;
+                    // not an invisible trail
+                    caret_no_trail = caret;
+                }
```
Comment (hecrj) [inline glyph-brush-layout/src/words.rs]: Nice. This should be faster too, right?

Comment (alexheretic) [reply glyph-brush-layout/src/words.rs]: Not much difference in the benchmarks, I assume the bounds are pre-computed anyway? But simpler & less buggy logic here is always welcome!
